home:
    pattern:  /
    defaults: { _controller: AgileInvoiceBundle:Default:index }

account:
    resource: "@AgileInvoiceBundle/Controller/AccountController.php"
    type: annotation

invoices:
    pattern:  /invoices
    defaults: { _controller: AgileInvoiceBundle:Invoices:index }

# clients:
#     pattern:  /clients
#     defaults: { _controller: AgileInvoiceBundle:Clients:index }

# clients_new:
#     pattern:  /clients/new
#     defaults: { _controller: AgileInvoiceBundle:Clients:new }

# clients_edit:
#     pattern:  /clients/{id}/edit
#     defaults: { _controller: AgileInvoiceBundle:Clients:edit }

# clients_contacts_new:
#     pattern: /clients/{id}/contacts/new
#     defaults: { _controller: AgileInvoiceBundle:Clients:newContact }

client:
    resource: "@AgileInvoiceBundle/Controller/ClientController.php"
    type: annotation

contact:
    resource: "@AgileInvoiceBundle/Controller/ContactController.php"
    type: annotation

invoices_archive:
    pattern:  /invoices/archive
    defaults: { _controller: AgileInvoiceBundle:Invoices:archive }

projects:
    pattern:  /projects
    defaults: { _controller: AgileInvoiceBundle:Projects:index }

recurring_invoices:
    pattern:  /recurring_invoices
    defaults: { _controller: AgileInvoiceBundle:Invoices:recurring }

estimates:
    pattern:  /estimates
    defaults: { _controller: AgileInvoiceBundle:Estimates:index }

invoices_configure:
    pattern:  /invoices/configure
    defaults: { _controller: AgileInvoiceBundle:Invoives:configure }
