home:
    pattern:  /
    defaults: { _controller: AgileInvoiceBundle:Default:index }

welcome:
    pattern:  /welcome
    defaults: { _controller: AgileInvoiceBundle:Default:welcome }

overview:
    pattern:  /overview
    defaults: { _controller: AgileInvoiceBundle:Default:overview }

invoices:
    pattern:  /invoices
    defaults: { _controller: AgileInvoiceBundle:Invoices:index }

client:
    resource: "@AgileInvoiceBundle/Controller/ClientController.php"
    type: annotation

contact:
    resource: "@AgileInvoiceBundle/Controller/ContactController.php"
    type: annotation

invoices_archive:
    pattern:  /invoices/archive
    defaults: { _controller: AgileInvoiceBundle:Invoices:archive }

projects:
    pattern:  /projects
    defaults: { _controller: AgileInvoiceBundle:Projects:index }

recurring_invoices:
    pattern:  /recurring_invoices
    defaults: { _controller: AgileInvoiceBundle:Invoices:recurring }

estimates:
    pattern:  /estimates
    defaults: { _controller: AgileInvoiceBundle:Estimates:index }

invoices_configure:
    pattern:  /invoices/configure
    defaults: { _controller: AgileInvoiceBundle:Invoives:configure }

user:
    resource: "@AgileInvoiceBundle/Controller/UserController.php"
    type: annotation