default:
    resource: "@AgileInvoiceBundle/Controller/DefaultController.php"
    type: annotation

user:
    resource: "@AgileInvoiceBundle/Controller/UserController.php"
    type: annotation

user_setting:
    resource: "@AgileInvoiceBundle/Controller/UserSettingController.php"
    type: annotation

company:
    resource: "@AgileInvoiceBundle/Controller/CompanyController.php"
    type: annotation

client:
    resource: "@AgileInvoiceBundle/Controller/ClientController.php"
    type: annotation

contact:
    resource: "@AgileInvoiceBundle/Controller/ContactController.php"
    type: annotation

invoices:
    resource: "@AgileInvoiceBundle/Controller/InvoiceController.php"
    type: annotation

recurring_invoices:
    pattern:  /recurring_invoices
    defaults: { _controller: AgileInvoiceBundle:Invoices:recurring }

projects:
    pattern:  /projects
    defaults: { _controller: AgileInvoiceBundle:Projects:index }

estimates:
    pattern:  /estimates
    defaults: { _controller: AgileInvoiceBundle:Estimates:index }

