home:
    pattern:  /
    defaults: { _controller: AgileInvoiceBundle:Default:index }

welcome:
    pattern:  /welcome
    defaults: { _controller: AgileInvoiceBundle:Default:welcome }

overview:
    pattern:  /overview
    defaults: { _controller: AgileInvoiceBundle:Default:overview }

invoices:
    resource: "@AgileInvoiceBundle/Controller/InvoiceController.php"
    type: annotation

client:
    resource: "@AgileInvoiceBundle/Controller/ClientController.php"
    type: annotation

contact:
    resource: "@AgileInvoiceBundle/Controller/ContactController.php"
    type: annotation

projects:
    pattern:  /projects
    defaults: { _controller: AgileInvoiceBundle:Projects:index }

recurring_invoices:
    pattern:  /recurring_invoices
    defaults: { _controller: AgileInvoiceBundle:Invoices:recurring }

estimates:
    pattern:  /estimates
    defaults: { _controller: AgileInvoiceBundle:Estimates:index }

user:
    resource: "@AgileInvoiceBundle/Controller/UserController.php"
    type: annotation