parameters:
#    agile_invoice.example.class: Agile\InvoiceBundle\Example

services:
#    agile_invoice.example:
#        class: %agile_invoice.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    agile_user.registration.form.type:
        class: Agile\InvoiceBundle\Form\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: agile_user_registration }
    agile_user.profile.form.type:
        class: Agile\InvoiceBundle\Form\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: agile_user_profile }
