parameters:
#    agile_invoice.example.class: Agile\InvoiceBundle\Example

    agile_invoice.currency_type_extension.class: Agile\InvoiceBundle\Form\Extension\CurrencyTypeExtension
    agile_invoice.user_factory.class: Agile\InvoiceBundle\Factory\UserFactory
    agile_invoice.company_factory.class: Agile\InvoiceBundle\Factory\CompanyFactory
    agile_invoice.user_setting_manager.class: Agile\InvoiceBundle\Model\UserSettingManager
    agile_invoice.user_setting.class: Agile\InvoiceBundle\Entity\UserSetting
    agile_invoice.company_preferences_form_type.class: Agile\InvoiceBundle\Form\Type\CompanyPreferencesFormType


services:
#    agile_invoice.example:
#        class: %agile_invoice.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    agile_invoice.currency_type_extension:
        class: %agile_invoice.currency_type_extension.class%
        arguments: [@translator]
        tags:
            - { name: form.type_extension, alias: currency }

    # Current User Factory
    agile_invoice.user_factory:
        class: "%agile_invoice.user_factory.class%"
        arguments: [@security.context]

    # Current User
    context.user:
        class: Agile\InvoiceBundle\Entity\User
        factory_service: agile_invoice.user_factory
        factory_method: get

    # Current Company Factory
    agile_invoice.company_factory:
        class: "%agile_invoice.company_factory.class%"
        arguments: [@context.user, @session, @doctrine.orm.default_entity_manager]

    # The Current Company
    context.company:
        class: Agile\InvoiceBundle\Entity\Company
        factory_service: agile_invoice.company_factory
        factory_method: get

    # Context Voter
    context.voter:
        class: Agile\InvoiceBundle\Security\Authorization\Voter\ContextVoter
        arguments:  ["@service_container"]
        public:     false
        tags:
            - { name: security.voter }

    agile_invoice.user_setting_manager:
        class: %agile_invoice.user_setting_manager.class%
        arguments:
            - @doctrine.orm.default_entity_manager
            - %agile_invoice.user_setting.class%
            - @context.user

    agile_invoice.company_preferences_form_type:
        class: %agile_invoice.company_preferences_form_type.class%
        arguments: [@translator]

    agile_user.registration.form.type:
        class: Agile\InvoiceBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: agile_user_registration }

    agile_user.profile.form.type:
        class: Agile\InvoiceBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: agile_user_profile }

    agile_user.user_registration_success:
        class: Agile\InvoiceBundle\EventListener\UserRegistrationSuccessListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }
