parameters:
#    agile_invoice.example.class: Agile\InvoiceBundle\Example

services:
#    agile_invoice.example:
#        class: %agile_invoice.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
