<?php

namespace Agile\InvoiceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{
    public function findAllOrderedByName()
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT c FROM AgileInvoiceBundle:Client c WHERE c.archived = :archived ORDER BY c.name ASC'
        )->setParameter('archived', 0);

        $clients = $query->getResult();

        return $clients;
    }

    public function findInactive()
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT c FROM AgileInvoiceBundle:Client c WHERE c.archived = :archived ORDER BY c.name ASC'
        )->setParameter('archived', 1);

        $clients = $query->getResult();

        return $clients;
    }

    // public function countInactiveClients()
    // {
    //     $em = $this->getEntityManager();
    //     $query = $em->createQueryBuilder()
    //         ->select('COUNT(c.archived) as archived')
    //         ->from('AgileInvoiceBundle:Client', 'c')
    //         ->where('c.archived = :archived')
    //         ->setParameter('archived', 1)
    //     ;

    //     $numArchivedClients = $query->getQuery()->getResult();

    //     return $numArchivedClients; 
    // }
}
