<?php

namespace Agile\InvoiceBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Agile\InvoiceBundle\Entity\Company;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
    public function findOneByIdAndCompany($id, Company $company)
    {
        $repository = $this->getEntityManager()->getRepository('AgileInvoiceBundle:Contact');
        $query = $repository->createQueryBuilder('c')
            ->where('c.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
        ;

        $contact = $query->getSingleResult();

        // Return the contact only if belongs to acual logged in user company
        if ($company == $contact->getClient()->getCompany()) {
            return $contact;
        }
        
    }
}
