<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130601181810 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE invoice (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, client_id INT DEFAULT NULL, number VARCHAR(20) DEFAULT NULL, po_number VARCHAR(50) DEFAULT NULL, tax NUMERIC(4, 2) NOT NULL, tax2 NUMERIC(4, 2) NOT NULL, issue_date DATE NOT NULL, due_date DATE NOT NULL, discount INT DEFAULT NULL, currency VARCHAR(3) NOT NULL, summary VARCHAR(255) DEFAULT NULL, note LONGTEXT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_90651744A76ED395 (user_id), INDEX IDX_9065174419EB6921 (client_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE invoice_category (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_19644399A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE invoice_item (id INT AUTO_INCREMENT NOT NULL, invoice_id INT DEFAULT NULL, category_id INT DEFAULT NULL, description LONGTEXT DEFAULT NULL, quantity NUMERIC(5, 2) NOT NULL, unitPrice NUMERIC(9, 2) NOT NULL, applyTax TINYINT(1) NOT NULL, applyTax2 TINYINT(1) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_1DDE477B2989F1FD (invoice_id), INDEX IDX_1DDE477B12469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE invoice ADD CONSTRAINT FK_90651744A76ED395 FOREIGN KEY (user_id) REFERENCES user_account (id)");
        $this->addSql("ALTER TABLE invoice ADD CONSTRAINT FK_9065174419EB6921 FOREIGN KEY (client_id) REFERENCES client (id)");
        $this->addSql("ALTER TABLE invoice_category ADD CONSTRAINT FK_19644399A76ED395 FOREIGN KEY (user_id) REFERENCES user_account (id)");
        $this->addSql("ALTER TABLE invoice_item ADD CONSTRAINT FK_1DDE477B2989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id)");
        $this->addSql("ALTER TABLE invoice_item ADD CONSTRAINT FK_1DDE477B12469DE2 FOREIGN KEY (category_id) REFERENCES invoice_category (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE invoice_item DROP FOREIGN KEY FK_1DDE477B2989F1FD");
        $this->addSql("ALTER TABLE invoice_item DROP FOREIGN KEY FK_1DDE477B12469DE2");
        $this->addSql("DROP TABLE invoice");
        $this->addSql("DROP TABLE invoice_category");
        $this->addSql("DROP TABLE invoice_item");
    }
}
