<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130516193032 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE client ADD user_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE client ADD CONSTRAINT FK_C7440455A76ED395 FOREIGN KEY (user_id) REFERENCES user_account (id)");
        $this->addSql("CREATE INDEX IDX_C7440455A76ED395 ON client (user_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE client DROP FOREIGN KEY FK_C7440455A76ED395");
        $this->addSql("DROP INDEX IDX_C7440455A76ED395 ON client");
        $this->addSql("ALTER TABLE client DROP user_id");
    }
}
