<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130420103734 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE contact ADD client_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE contact ADD CONSTRAINT FK_4C62E63819EB6921 FOREIGN KEY (client_id) REFERENCES client (id)");
        $this->addSql("CREATE INDEX IDX_4C62E63819EB6921 ON contact (client_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE contact DROP FOREIGN KEY FK_4C62E63819EB6921");
        $this->addSql("DROP INDEX IDX_4C62E63819EB6921 ON contact");
        $this->addSql("ALTER TABLE contact DROP client_id");
    }
}
