<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130604071646 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE company (id INT AUTO_INCREMENT NOT NULL, owner_id INT DEFAULT NULL, name VARCHAR(100) NOT NULL, subscription_plan VARCHAR(100) DEFAULT NULL, billing_info VARCHAR(100) DEFAULT NULL, receipt_recipients VARCHAR(255) NOT NULL, receipts VARCHAR(100) DEFAULT NULL, fiscal_year_start VARCHAR(100) NOT NULL, timezone VARCHAR(100) DEFAULT NULL, date_format VARCHAR(100) DEFAULT NULL, currency VARCHAR(3) NOT NULL, currency_placement VARCHAR(100) DEFAULT NULL, include_currency_code TINYINT(1) NOT NULL, number_format VARCHAR(100) DEFAULT NULL, color_scheme VARCHAR(100) DEFAULT NULL, logo VARCHAR(100) DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, UNIQUE INDEX UNIQ_4FBF094F7E3C61F9 (owner_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE company ADD CONSTRAINT FK_4FBF094F7E3C61F9 FOREIGN KEY (owner_id) REFERENCES user_account (id)");
        $this->addSql("ALTER TABLE user_account ADD CONSTRAINT FK_253B48AE979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE user_account DROP FOREIGN KEY FK_253B48AE979B1AD6");
        $this->addSql("DROP TABLE company");
    }
}
